### ISSUE TITLE
Some questions about the program

### ISSUE THREAD

**Issue by lljjdxh** [alainmuls/pyRTKLib#5]
Hello, are you still doing the work related to beidou?
There are some questions:
1，I found some applications missing from the file package, such as convbin, sbf2rin, etc.So, could you give me a download link or something;
2，Where is the program related to the location part? I can't find it.
3，I would like to ask which type of receiver front end you are using.

**Comment by alainmuls** [comment]
Hi,

Sorry I didn't see your question until now.
I do not use BEIDOU, only GPS and Galileo processing.

The specific programs are either proprietary (from Septentrio Satellite Navigation) so that I cannot distribute it myself. Check their website for possible download.

For the location part I used RTKLib which is open source, but I am now passing to another program gLAB which is much better detailed.

I use Septentrio receivers, but also uBlox receivers and convert the binary files to RINEX first

bye/Alain

**Comment by lljjdxh** [comment]
Ok, I get part of it.Thank you very much for your reply.
